### PR TITLE
UI Fixes & Changes + README Update

### PR DESCRIPTION
**Pull request by CREEATION**
//e: nothing works

I can git so good! (No idea what I've done with the commits and merges lul)

**[Preview](https://i.imgur.com/s4HtdFT.png)**

# Changes summary:

## Improve Tab Management
Close tabs with your middle mouse button. If the closed tab was active, the very next tab opens automatically.

## Add "file open" indicator + possible UI change (open for thoughts 💃)
Also added "click on an already open file again to close it", so one can quickly open & check a file and then close it by just clicking again.

## Quick UI fix
Flexbox = evil. Too many tabs open would lead to the editor being stretched to hell.

### CODE REVIEW

**Comment by CREEATION** [comment]
I also wanted to add a "is-active" class to the file entry which is currently open, but didn't manage to do so.
The class already exists: https://github.com/eiszfuchs/lo-rez-editor/pull/2/commits/e44f84b76c0f997b35313cd535f59917bfc5637f#diff-ba0a98deb7ffb006e2238c307203acbaR197

**Comment by eiszfuchs** [comment]
Hello @CREEATION and thanks for your contribution!

Changes I hadn't pushed until just recently and changes you've made overlap, that's why your branch is currently in conflict with `master`.

I'll go through your changes and see if we can resolve this easily!

-   The `README` changes are good, we just need to clean up the formatting and go even deeper with it.

-   >   Close tabs with your middle mouse button. 
    
    I like this change a lot. I was developing on Mac most of the time, so I had no middle mouse button, but I can see its use.

-   >   click on an already open file again to close it
    
    I can see why this might be useful, but until we have a proper undo/redo and safety on dirty states of editors, we shouldn't just close already open editors by clicking on it in the resource list, just because we could kill unsaved changes on accidental clicks.

    We might need to find a solution for this, as it also might invalidate the editor tabs at the top of the window. (And that might be for the better!)

-   >   Flexbox = evil.

    Not per se. That's the change our branches overlap. I made it so that tabs could shrink and labels overflow, so tabs wouldn't stretch the interface, but get smaller if more editors are open.

    If we get rid of the tabs altogether, that hack would not be necessary anymore.

There's a lot of potential here. 🤔 
Do you want to clean up your working copy (rebase, resolve conflicts and squash commits) or are you okay with me taking your remaining changes and merging them manually into my code?

**Comment by CREEATION** [comment]
Take what's useful manually! 🐢

**Comment by eiszfuchs** [comment]
Will do!

**Comment by eiszfuchs** [comment]
Please review the latest version and verify every important feature has been added.

Close if this is done, thank you! 💪

**Comment by CREEATION** [comment]
All good 🥇

**Pull request closed without merging**
